language: java
jdk:
  - openjdk8
services:
  - docker
# env:
#   global:
#     secure: IMAGE_NAME
#     secure: HEROKU_API_KEY
#     secure: DOCKER_USER
#     secure: DOCKER_PASS
# replace the following env configurations with your own
env:
  global:
    - secure: cKjATeodKDrn3cj9MILKmWHAN+fl18oyXnMGGH71rgac4wPGRbvHOM1aQalTB3/VAmGsK1FNj/Yj+Vatmw2GJakF33me3CYeJVZIr5JjqjFtkuoVVnbrFes8N0tlp9H/dr60tUXdp6ABlYljD7BS+X3zBWntEAwrb8o9rjhsmwVDCVCxNt76j9RUzm9eO9MVGwEpG0sA/JOal853o9q5XaC2oRiTwikY5i6FUoCq+RoJDLDoqWiY6nQROtYAxQpVP3UxWrHOB2pBh+P6KwrpDBTUis42oyKeGuSPZajqBu73/K8BsMjfKSapZ+nx0A1ycRuzD7bg4YAVo6d9qCGZi7ZGdD/sIKljGvkPBenep6+YNPCVSnCgkhWMDcLsDzrp0QJA5zNG+M168FRB4GH5vJcyeYw0x2C4emdHpigKqQKA9tYRgoodMu3tPECIQcS4qBFJ6R/ihwsabE0LQg2aXbPAR2tVxJvnqLP7RIhfzJ2lTo6fIuTJ5EFh1ATtBj6opDfK5xSfFSjsFSXdQgJreydS/2Og3AsAxIgs8YGkv1CpOdgeWIx3sFdKjSDqhibiVvPxam1mY+0fRrnMq2dsd8riyxIwanj8Lk006MG+x2uHtNghCEJBKYHdN1wYuSIsjAkszkryxA6T1TfB+gjuwan7m/tYdiCW6TY3rXa0DtQ=
    - secure: f5oQtpm+5fZEe4MCKPUhu9BqXJf+1zksMfk23jCVwpOgI9txgv6BX0PL4fY6IdI5T5pb8OcQxX3hIKcXpIpIxZPZ/gOYr2yUuR2fePC9h9FRH9IyYaTgF+RPIu3aXMAGLopVKtF0BGArvN7u+C7CPJE/37fJ1aHLc4vn/rUcnaPhqZYDjzXDi4hHrMWgON0MLffJ5iyH27Zi6BD6Y31/WBRI2mXkhV81XKa+EACk54vxDJQttOOuqrADuT2I7/M4PwYx+c8nZkK29ySj/irGwjenFGqMcU4HXqrapBzugfxOauWIpQwVa7KXIHv+IOBWXRzqwePc5TXN92pRBFIEcJ09+0DdImEnOUc4mWfSsQhJkYxQYxWJ0geWzAXuL1I6z6UVP2asaxyBP6c6C2YMsYbgNjlqcdWAjmsSoSlhYy89XdgQbzFmR1UeOV3bzF40xkPdVQoI2yz8yetw/9a/QFPxeu9xSvQarAtgo2WW0HVxWSlmx4o3M+T7KbBhLDcZle+XEQLRQBe5rPp+N+3P3DNwWMhL6kskitecYEqT+4L+vx1HJPD/GnbBk7EFkOY8r51kgQ5PoqAZ2GTyVGj+OCQiqXzr2LTmM0pvhgWnVSCHKgE1Ds8xrNhENIwW+Iwez4XRtosbqy6aErep+oGCjJd44ApvWr5wjMv45a+WBG0=
    - secure: ogVX8UGqYEYOkQvhYsfBHKGpNUixq1ZDA4SzJmghlnfgpW77F31pfFJcEkPSbfu6ultKQ0a2vqPKeQyDICccKewD5lwkP82761EGc/oV9wCMNrjPACfxwEXFrTh7ToKC9uI0cvze1J7D4wxbthjJY3LhRrRfVx1tg6li1+ZbLGtBq7O20ydoz5JDJYiQDiqOajbQC/txHB/8VU4ebwzIvyZwCLYDV8czZVaGQlEZ8xVSL4XD3D3ar8aQQiuIE+rz3yKWHnzK+6xYSc7GCHjzo5Xjm2T7yy0UbF6snVt27ndPYKtnHOogPw1D2J/LUrr+4BnOLzLp8FTTh8rerr8XwFC2kJ9SXDtPDmR0JX04FYF9QItpJqu2g51PlCCuo/r9z+wQq+lgOwdLoKWW5HWIsQTtvAJEsLjs2yVIg9yMHDyTCCPOJyV3z8lm2bg1RwWKm1a2YGdHChqigPbC4ansENcwg+olSFJ1ZgUCnzPEI+rKoaJUGEECgkLX+n3At64TM3KEPBFV+ENJSRqSkfwxfLMHAlt0/1lRdolJVZY973K3+kCk8mrjVXdd3c+g3CE5pnj/Jm68J/DtzT24iQzg+h5+VDQoqQaX13r3YqtaRFtof0xKCrBxDgQNkXwdUlqwbmVd0X4qj1RpUNo0eXKHsdosqohUT8y9S3qshIAwh0U=
    - secure: Ew4/Bd0vhMGPTONCJ45om0yVXO7HIW0UK22qkqWvVERwL444ksnPLLywZaKTxuyY6aJFn8uXRur9Rl6KM2mQxfdq9tpuSIp+yMuIrdmMAqJOUw5mUgrfhtaS++s9rzGesiYKMY9J/YvOVgi/M5Doxvf4P0ZELtCHsctzt+ETZuLrMD9+Xk4uUo+AaZPwjVH/VynWbZGlnsb11wz2+UqahE/GCjrEISKsPYvRbAeMe6Da35Xxr968d+A89rIrK/Aap4p2ngzotCHmzxVOpiC1etzhx9oKTMOwqCEqDYVxWiW3vYRbzr9YfmvpWUKXdOe6ZWpisEQrCJThycKjpPUjmrraxcEkB0YP6smiRt28lDON8k9lkk8amGVv/bivTHy1p5TXUOvV7xExapjaAbVp2fiIZQsI0hfUwSql1kN6m38Nx6Vrsp3rKFdPvKlM32u79J8Viw1detYqNMvRvn0x9Gao6aBT3ILg2x03CYmWtja1fl2Gti7XukZ28LxAmd4YcGIFz3ENID6hrfk5E0DhsZTV1sgNKWjGIP8eCj6T6rGHaKnm796SZIr4n8QxKGob9/m0QDCN8obNYYqlO34OlmAK8K7VuEbZE7kKmemHZpQTtTQswrm75gli2ZQVGnYB4wqU3qE4PWdsE/QGKfi0olq5lJE6wnuI/0QiKOC+PsE=
#before_install:
#  - docker pull openjdk:8-jdk-alpine
# Test & Build SpringBoot app
script:
  - mvn clean package
# Create Docker image for our app and push it to Dockerhub repository and send messages to the Teams channel after the `script` job is successfully executed
after_success:
  - export COMMIT=${TRAVIS_COMMIT::7}
  - export TAG=`if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$TRAVIS_BRANCH--$COMMIT"; fi`
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker-compose build
  - docker tag pawankulkarni/pawan-helloworld:latest pawankulkarni/pawan-helloworld:$TAG
#  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
#  - docker push $IMAGE_NAME:$TAG
  - docker push pawankulkarni/pawan-helloworld:$TAG
# If the `script` job fails, it will send a failure message to Teams channel
after_failure:
  - export TITLE="Travis:$TRAVIS_JOB_ID -- build job is failed"
  - export TEXT=[datetime]:`date`
# Allow Travis to help deploy the app on Heroku
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.10.0
deploy:
  provider: heroku
  api-key: ${HEROKU_API_KEY}
  app: pawan-helloworld
  on:
    all_branches: true